name: Check run ID tests
on:
  workflow_dispatch:

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - id: get-check-run-id
          name: Get Check Run ID
          env:
            CHECK_RUN_ID: ${{ job.check_run_id }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GH_TOKEN}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/actions/jobs/${CHECK_RUN_ID}"
            echo "GitHub job check run ID: ${CHECK_RUN_ID}"
        - id: get-job-id
          name: Get Job ID variable
          run: |
            echo "GitHub job ID: ${GITHUB_JOB}"

