name: Job Context - Matrix Strategy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  matrix-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 18, 20]
        include:
          - os: ubuntu-latest
            node-version: 20
            experimental: true
      fail-fast: false
    steps:
      - name: Display matrix context
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Node Version: ${{ matrix.node-version }}"
          echo "Job ID: ${{ github.job }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: Display if experimental
        if: matrix.experimental == true
        run: echo "This is an experimental configuration"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verify Node.js version
        run: node --version

      - name: Display full job context
        run: echo '${{ toJSON(job) }}'

  summarize-matrix:
    runs-on: ubuntu-latest
    needs: matrix-job
    if: always()
    steps:
      - name: Display matrix results
        run: |
          echo "Matrix job completed"
          echo "Matrix job result: ${{ needs.matrix-job.result }}"
          echo "Current job status: ${{ job.status }}"
