name: Job Context - Status Handling

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  job-with-success:
    runs-on: ubuntu-latest
    steps:
      - name: Successful step
        run: echo "This step will succeed"

      - name: Check job status
        run: echo "Current job status is ${{ job.status }}"

  job-with-failure:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Step that will fail
        run: exit 1
        continue-on-error: true

      - name: Check status after failure
        if: always()
        run: |
          echo "Job status: ${{ job.status }}"
          echo "This runs even after the previous step failed"

  cleanup-job:
    runs-on: ubuntu-latest
    needs: [job-with-success, job-with-failure]
    if: always()
    steps:
      - name: Display final status
        run: |
          echo "Job with success status: ${{ needs.job-with-success.result }}"
          echo "Job with failure status: ${{ needs.job-with-failure.result }}"
          echo "Current job status: ${{ job.status }}"

      - name: Conditional cleanup based on previous job results
        if: needs.job-with-failure.result == 'failure' || needs.job-with-failure.result == 'success'
        run: echo "Performing cleanup regardless of previous job outcomes"
